name: Create Release and Build Docker Image

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions: write-all

jobs:
  create-release-and-build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get the latest tag
        id: get_tag
        run: echo ::set-output name=tag::$(git describe --tags `git rev-list --tags --max-count=1`)

      - name: Bump version and push tag
        id: tag_version
        run: |
          NEW_TAG=$(cat VERSION)
          echo "New tag is $NEW_TAG"
          echo "::set-output name=NEW_TAG::$NEW_TAG"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag -a $NEW_TAG -m "Release $NEW_TAG"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin $NEW_TAG
        env:
          VERSION: ${{ steps.get_tag.outputs.tag }}

      - name: Debug NEW_TAG
        run: echo "The new tag is $NEW_TAG"

      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.NEW_TAG }}
          release_name: ${{ steps.tag_version.outputs.NEW_TAG }}
          body: ${{ github.event.pull_request.body }}
          draft: false
          prerelease: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image with tag
        run: |
          TAG=${{ steps.tag_version.outputs.NEW_TAG }}
          docker build -t naotokubota/shiba:$TAG -t naotokubota/shiba:latest -f docker/Dockerfile .
          docker push naotokubota/shiba:$TAG
          docker push naotokubota/shiba:latest
